# Generated by Django 3.1.6 on 2021-02-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elsoapp', '0002_auto_20210210_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tanulo',
            old_name='jelszó',
            new_name='jelszo',
        ),
    ]
